from dotenv import load_dotenv
import os

# load environment keys
load_dotenv()

DATABASE_HOST = os.getenv("OPENSEARCH_DATABASE_HOST", "")
DATABASE_USERNAME = os.getenv("OPENSEARCH_DATABASE_USERNAME", "")
DATABASE_PASSWORD = os.getenv("OPENSEARCH_DATABASE_PASSWORD", "")
SCRAPE_TARGET_URL = os.getenv("SCRAPE_TARGET_URL", "")

TELEGRAM_BOT_API_TOKEN = os.getenv("TELEGRAM_BOT_API_TOKEN", "")

SUBSCRIBER_NOTIFICATION_INTERVAL_HOURS = int(
    os.getenv("SUBSCRIBER_NOTIFICATION_INTERVAL_HOURS", 2)
)
WEBSITE_SCRAPING_INTERVAL_HOURS = int(os.getenv("WEBSITE_SCRAPING_INTERVAL_HOURS", 12))
